from openai import AzureOpenAI
import os
from datetime import datetime
import subprocess

# 1. Automatically get today's date
today_str = datetime.now().strftime("%Y-%m-%d")
report_path = f"/tmp/server_report_{today_str}.txt"
# report_path = f"/tmp/server_report_2025-07-07.txt"

# 2. Read today's monitoring log
with open(report_path) as f:
    report = f.read()

# 3. Create the prompt for the model
prompt = f"""
You are an assistant helping a system administrator. Based on the server monitoring logs below, generate a concise daily summary report including:

1. List of unreachable servers
2. GPU usage per server (include user, memory, and PID if available)
3. Disk usage details (highlight any volumes with >80% usage)
4. Slurm cluster queue summary
5. Final health check summary and any action recommendations

Monitoring log:
{report}
"""

# 4. Call Azure OpenAI to generate the report
endpoint = "https://mgh-camca-research-private-e2-openai-service.openai.azure.com/"
model_name = "gpt-4.1-nano"
deployment = "gpt_41_nano_2025_04_14"
subscription_key = ""
api_version = "2024-12-01-preview"

client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=subscription_key,
)

response = client.chat.completions.create(
    model=deployment,
    messages=[{"role": "user", "content": prompt}],
    temperature=0.3
)

# 5. Get the generated content
generated_content = response.choices[0].message.content.strip()

# 6. Add the header line
final_report = f"Generated By GPT-4.1-nano\n\n{generated_content}"

# 7. Save the result to /tmp
tmp_output_path = f"/tmp/summary_report_{today_str}.txt"
with open(tmp_output_path, "w") as f:
    f.write(final_report)

# 8. Append the result to a persistent log file in the home directory
home_log_path = os.path.expanduser("/home/local/PARTNERS/zl8/camca_resource_monitor/daily_summary_log.txt")
with open(home_log_path, "a") as f:
    f.write(f"\n===== {today_str} =====\n")
    f.write(final_report + "\n")

# 9. Use 'mail' to send the report by email
def send_email_with_mail(subject, body, to_addrs):
    # This uses the 'mail' command available on most Linux systems
    command = ["mail", "-s", subject] + to_addrs
    p = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        encoding="utf-8"
    )
    p.communicate(input=body)

send_email_with_mail(
    subject=f"Server Daily Summary - {today_str}",
    body=final_report,
    to_addrs=["abc@example.com", "cba@example.com"]
)

print("Report generated, saved, and emailed successfully.")


